#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/qbtee --profile=/etc/qbtee.d > /dev/null 2>&1 & echo "qbtee is started"
}

stop() {
	killall qbtee
	echo "qbtee is stoped"
}

restart() {
	stop
	start
}
