#!/bin/sh

. /lib/functions.sh

# 若非 r2s 则直接退出
board_name | grep -qF 'nanopi-r2s' || exit 0

# yes, disable tx rx on gmac, not the usb-net
# ethtool -K eth0 tx off rx off
ethtool -K eth1 tx-scatter-gather-fraglist off

irq=$(grep -m1 " xhci-hcd:usb3\$" /proc/interrupts | sed -n -e 's/^ *\([^ :]\+\):.*$/\1/p')
echo "8" > /proc/irq/${irq}/smp_affinity

echo "7" > /sys/class/net/eth1/queues/rx-0/rps_cpus
echo "7" > /sys/class/net/eth1/queues/tx-0/xps_cpus
