#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/filebrowser -d /etc/filebrowser.db > /dev/null 2>&1 & echo "filebrowser is started"
}

stop() {
	killall filebrowser
	echo "filebrowser is stoped"
}

restart() {
	stop
	start
}
