#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/frps -c /etc/frps.ini > /dev/null 2>&1 & echo "frps is started"
}

stop() {
	killall frps
	echo "frpc is stoped"
}

restart() {
	stop
	start
}
