#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/ohttps -c /etc/ohttps/ohttps.yaml > /dev/null 2>&1 & echo "ohttps is started"
}

stop() {
	killall ohttps
	echo "ohttps is stoped"
}

restart() {
	stop
	start
}
