#!/bin/sh /etc/rc.common

START=99
STOP=15

start() {
	/usr/bin/frpc -c /etc/frpc/frpc.yaml > /dev/null 2>&1 & echo "frpc is started"
}

stop() {
	killall frpc
	echo "frpc is stoped"
}

restart() {
	stop
	start
}
