#!/bin/sh /etc/rc.common

START=100
STOP=14

start() {
	/usr/bin/cqhttp -c /etc/cqhttp.yml -w /etc/cqhttp.d > /dev/null 2>&1 & echo "cqhttp is started"
}

stop() {
	killall cqhttp
	echo "cqhttp is stoped"
}

restart() {
	stop
	start
}

instal() {
	mkdir -p /etc/nb-cli
	cd /etc/nb-cli
	nb create

	nb plugin install nonebot-plugin-gocqhttp
	git clone https://github.com/CMHopeSunshine/LittlePaimon
}
